#spring.datasource.url=jdbc:sqlite:todo.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.properties.hibernate.query.sql.syntax=sqlite

spring.datasource.url=jdbc:postgresql://localhost:5432/rigel_electronic_cloud_test
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.datasource.url=jdbc:hsqldb:file:./data/localdb;shutdown=true
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
#spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
#spring.jpa.hibernate.ddl-auto=update


