server.port=8089

spring.datasource.url=jdbc:postgresql://localhost:5435/rigel_electronic_cloud
spring.datasource.username=rkrigelsoft
spring.datasource.password=Rk!@#121
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


